services:
  telethon_downloader:
    build: .
    #image: jsavargas/telethon_downloader
    container_name: telethon_downloader
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - PERMISSIONS_FOLDER=777
      - PERMISSIONS_FILE=755
      - TZ=Europe/Madrid
      - APP_LANGUAGE=es_ES                              # OPTIONAL
      - TG_UNZIP_TORRENTS=True                          # OPTIONAL (True/False)
      - ENABLED_UNZIP=True                              # OPTIONAL (True/False)
      - ENABLED_UNRAR=True                              # OPTIONAL (True/False)
      - TG_MAX_PARALLEL=4                               # OPTIONAL
      - TG_DL_TIMEOUT=4600                              # OPTIONAL
      - TG_PROGRESS_DOWNLOAD=True                       # OPTIONAL (True/False)
      - PROGRESS_STATUS_SHOW=10                         # OPTIONAL
      - YOUTUBE_FORMAT_AUDIO=bestaudio/best             # OPTIONAL
      - YOUTUBE_FORMAT_VIDEO=bestvideo+bestaudio/best   # OPTIONAL
      - YOUTUBE_DEFAULT_DOWNLOAD=VIDEO                  # OPTIONAL (AUDIO/VIDEO) 
      - YOUTUBE_DEFAULT_EXTENSION=MKV                   # OPTIONAL (mkv/mp4) 
      - YOUTUBE_SHOW_OPTION=True                        # OPTIONAL (True/False)
      - YOUTUBE_TIMEOUT_OPTION=5                        # OPTIONAL
      - YOUTUBE_AUDIO_FOLDER=/youtube/audio             # OPTIONAL
      - YOUTUBE_VIDEO_FOLDER=/youtube/video             # OPTIONAL
    volumes:
      - ./config:/config
      - ./download:/download
      - ./Películas:/Películas
      - ./Series:/Series
      - ./torrent/watch:/watch

